const PLUS_OPERATOR = "+";
const MINUS_OPERATOR = "-";
const MULTIPLY_OPERATOR = "*";
const DIVIDE_OPERATOR = "/";
const OPERATORS = [PLUS_OPERATOR, MINUS_OPERATOR, MULTIPLY_OPERATOR, DIVIDE_OPERATOR];

module.exports = {
  PLUS_OPERATOR,
  MINUS_OPERATOR,
  MULTIPLY_OPERATOR,
  DIVIDE_OPERATOR,
  OPERATORS
};